---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aeraki-dubbo
  labels:
    app: aeraki-dubbo
spec:
  selector:
    matchLabels:
      app: aeraki-dubbo
  replicas: 1
  template:
    metadata:
      labels:
        app: aeraki-dubbo
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: aeraki-dubbo
          image: aeraki/aeraki-dubbo
          imagePullPolicy: Always
          env:
            - name: istiodAddr
              value: "istiod.istio-system:15010"
            - name: listeningAddr
              value: ":1109"
          ports:
            - containerPort: 1109

---
apiVersion: v1
kind: Service
metadata:
  name: aeraki-dubbo
spec:
  selector:
    app: aeraki-dubbo
  ports:
    - name: tcp-mcp
      port: 1109
      protocol: TCP
      targetPort: 1109
